# Generated by Django 5.0 on 2024-07-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_comment_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='disinterest',
            field=models.IntegerField(default=0),
        ),
    ]
