exclude: .*migrations\/.*

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/djlint/djLint
    rev: v1.34.1
    hooks:
      - id: djlint-reformat-django
        args: [--configuration, .djlintrc]
      - id: djlint-django
        args: [--configuration, .djlintrc]
