version: '3'

services:
  app:
    image: hn-django:latest
    command: gunicorn project.wsgi --bind 0.0.0.0:8000
    volumes:
      - .:/app:Z
    networks:
      - backend

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:Z
      - ./_static:/app/_static:Z
    depends_on:
      - app
    ports:
      - "8000:80"
    networks:
      - frontend
      - backend
   
networks:
  frontend:
  backend:
