# Generated by Django 5.0 on 2024-07-06 13:06

import clickhouse_backend.models
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', clickhouse_backend.models.StringField(default='', max_length=255)),
                ('session_id', clickhouse_backend.models.StringField(default='', max_length=255)),
                ('event_type', clickhouse_backend.models.EnumField(choices=[(1, 'Engagement'), (2, 'Page View'), (3, 'Htmx View'), (4, 'Feed Impression'), (5, 'Register'), (6, 'Login'), (7, 'Verify'), (99, 'Custom')], default=99)),
                ('engagement_type', clickhouse_backend.models.EnumField(choices=[(0, 'None'), (1, 'Interest'), (2, 'Quality'), (3, 'Disinterest')], default=0)),
                ('url', clickhouse_backend.models.StringField(default='', low_cardinality=True, max_length=1024)),
                ('referrer', clickhouse_backend.models.StringField(default='', low_cardinality=True, max_length=1024)),
                ('user_agent', clickhouse_backend.models.StringField(default='', low_cardinality=True, max_length=1024)),
                ('ip_address', clickhouse_backend.models.GenericIPAddressField(default='::')),
                ('event_time', clickhouse_backend.models.DateTime64Field()),
                ('metadata', clickhouse_backend.models.StringField(default='', max_length=1024)),
                ('created_at', clickhouse_backend.models.DateTime64Field()),
                ('engagement_score', clickhouse_backend.models.Int32Field(blank=True, default=None, null=True)),
            ],
            options={
                'ordering': ['-event_time'],
                'engine': clickhouse_backend.models.MergeTree(enable_mixed_granularity_parts=1, index_granularity=1024, index_granularity_bytes=1048576, order_by=('event_time', 'user_id'), partition_by=clickhouse_backend.models.toYYYYMMDD('event_time'), primary_key='event_time'),
                'indexes': [clickhouse_backend.models.Index(fields=['user_id'], granularity=4, name='user_id_set_idx', type=clickhouse_backend.models.Set(1000)), clickhouse_backend.models.Index(fields=['session_id'], granularity=4, name='session_id_set_idx', type=clickhouse_backend.models.Set(1000)), clickhouse_backend.models.Index(fields=['ip_address'], granularity=1, name='ip_bloom_idx', type=clickhouse_backend.models.BloomFilter(0.001)), clickhouse_backend.models.Index(fields=['event_type'], granularity=4, name='event_type_idx', type=clickhouse_backend.models.Set(1000)), clickhouse_backend.models.Index(fields=['engagement_type'], granularity=4, name='engagement_type_idx', type=clickhouse_backend.models.Set(1000))],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
