# Generated by Django 5.0 on 2024-07-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interest',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('interest__gte', 0)), name='users_user_interest_gte_0'),
        ),
    ]
