# Generated by Django 5.0 on 2024-07-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_user_interest_user_users_user_interest_gte_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disinterest',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('disinterest__gte', 0)), name='users_user_disinterest_gte_0'),
        ),
    ]
