# Generated by Django 5.0 on 2024-07-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='interest',
            field=models.IntegerField(default=0),
        ),
    ]
